# Generated by Django 2.0.10 on 2019-01-05 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField()),
                ('f_name', models.CharField(max_length=20)),
                ('l_name', models.CharField(max_length=20)),
                ('address_1', models.CharField(max_length=30)),
                ('address_2', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('post_code', models.CharField(max_length=10)),
                ('tel_no', models.CharField(max_length=15)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='furniture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('furniture_id', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('purchase_date', models.DateField(auto_now=True)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('purchase_customer_id', models.IntegerField()),
                ('item_sold', models.BooleanField()),
                ('sale_date', models.DateField()),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('sale_customer_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('furniture_id', models.IntegerField()),
                ('image_id', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
