# Generated by Django 2.0.10 on 2019-01-05 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodasnew', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniture',
            name='furniture_id',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='item_sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='sale_customer_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='sale_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
